apiVersion: v1
kind: Namespace
metadata:
  name: fgc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiapcloudgames-api-gateway
  namespace: fgc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiapcloudgames-api-gateway
  template:
    metadata:
      labels:
        app: fiapcloudgames-api-gateway
    spec:
      containers:
      - name: fiapcloudgames-api-gateway
        image: ${IMAGE}  # Mudado para usar variável do workflow
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: USERS_API_URL
          value: http://fiapcloudgames-users-api.fgc.svc.cluster.local
        - name: ORDERS_API_URL
          value: http://fiapcloudgames-orders-api.fgc.svc.cluster.local
        - name: GAMES_API_URL
          value: http://fiapcloudgames-games-api.fgc.svc.cluster.local
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: fiapcloudgames-api-gateway
  namespace: fgc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer  # Mudado de NodePort para LoadBalancer
  selector:
    app: fiapcloudgames-api-gateway
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fiapcloudgames-api-gateway-hpa
  namespace: fgc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fiapcloudgames-api-gateway
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
